name: CD Pipeline

on:
  workflow_dispatch:
    inputs:
        image_tag:
            description: 'Image tag to deploy'
            required: true
        helm_chart_version:
            description: 'Helm chart version to deploy'
            required: true

jobs:
    deploy:
        uses: Grupo-118-Tech-Challenge-Fiap-11SOAT/terraform-template-pipeline-grupo118-fase-3/.github/workflows/dotnet-cd-template.yml@develop
        with:
          helm_chart_version: ${{ github.event.inputs.helm_chart_version }}
          helm_chart_name: "grupo118fase4"
          helm_values_file: "helm/values-production.yaml"
          secrets_mapping: |
              {
                  "POC_IMAGE_TAG": "${{ github.event.inputs.image_tag }}",
                  "POC_DATABASE_HOST": "${{ secrets.POC_DATABASE_HOST }}",
                  "POC_DATABASE_PORT": "${{ secrets.POC_DATABASE_PORT }}",
                  "POC_DATABASE_NAME": "${{ secrets.POC_DATABASE_NAME }}",
                  "POC_API_KEY": "${{ secrets.POC_API_KEY }}"
              }