name: CI/CD Pipeline
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  ci:
    uses: Grupo-118-Tech-Challenge-Fiap-11SOAT/terraform-template-pipeline-grupo118-fase-3/.github/workflows/dotnet/ci-template.yml@develop
    with:
      sonar-project-key: "poc-api-dotnet-cicd-template-usage-fase4"
      sonar-organization: "grupo-118-tech-challenge-fiap-11soat"
      solution-path: "."
      test-projects: "**/*Tests.csproj"
      dotnet-version: "8.0.x"
      build-configuration: "Release"
      dockerfile-path: "./poc-api-dotnet-cicd-template-usage-fase4/Dockerfile"
      image-name: "poc-api-dotnet-cicd-template-usage-fase4"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      ACR_REGISTRY: ${{ secrets.ACR_REGISTRY }}